#!/bin/bash

source /opt/ros/melodic/setup.bash
roscore &

sleep 1

ssh -oStrictHostKeyChecking=no -f -R \*:$(echo $PORT):localhost:8080 -N andre@34.74.191.20 &

sleep 1

cd /home/py3_cv_bridge_ws
source install/setup.bash --extend
python3 ../pyrtc_ros/pyrtc_ros.py &

sleep 1

xvfb-run -s "-screen 0 1280x1024x24" rosrun gazebo_ros gzserver --verbose /worlds/iris_arducopter_runway.world &

sleep 1

/home/ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-iris -w
