#!/bin/bash

docker kill $(docker ps -a -f ancestor=andremyers/drones:latest -q -f status=running)
status=$?;
if [ $status -eq 0 ]; then
	echo 'Waiting for containers to shutdown';
	sleep 2
	echo 'Removing containers killed on shutdown and any previosuly unremoved:';
	docker rm $(docker ps -a -f ancestor=andremyers/drones:latest -q -f status=exited);
elif [ $status -ne 0 ]; then
	echo 'Removing previously unremoved containers:';
	docker rm $(docker ps -a -f ancestor=andremyers/drones:latest -q -f status=exited)
fi
exit 0
